### ISSUE TITLE
Editing a User from the Admin Page fails with JS Error

### ISSUE THREAD

**Issue by brianghig** [Asymmetrik/mean2-starter#49]
Steps to reproduce (from latest `staging` branch):

* Create a new user (using `local` strategy for local username/password authentication)
* Navigate to the Users Admin page at ../#/admin/users
* Click the `Edit User` button (pencil with rectangle icon)
* Observe that a JS error occurs and you are not taken to the User Profile page

JS Stacktrace:
```
(unknown) EXCEPTION: Uncaught (in promise): TypeError: Cannot set property 'name' of undefined
TypeError: Cannot set property 'name' of undefined
    at new EmptyError (eval at <anonymous> (http://localhost:3000/dev/vendor.js:730:1), <anonymous>:21:30)
    at FirstSubscriber._complete (eval at <anonymous> (http://localhost:3000/dev/vendor.js:3164:1), <anonymous>:148:31)
    at FirstSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:3000/dev/vendor.js:181:1), <anonymous>:114:18)
    at MergeAllSubscriber._complete (eval at <anonymous> (http://localhost:3000/dev/vendor.js:535:1), <anonymous>:94:30)
    at MergeAllSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:3000/dev/vendor.js:181:1), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:3000/dev/vendor.js:181:1), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:3000/dev/vendor.js:181:1), <anonymous>:114:18)
    at EmptyObservable._subscribe (eval at <anonymous> (http://localhost:3000/dev/vendor.js:476:1), <anonymous>:69:24)
    at EmptyObservable.Observable.subscribe (eval at <anonymous> (http://localhost:3000/dev/vendor.js:153:1), <anonymous>:45:27)
    at Observable._subscribe (eval at <anonymous> (http://localhost:3000/dev/vendor.js:153:1), <anonymous>:103:28)
    at MapOperator.call (eval at <anonymous> (http://localhost:3000/dev/vendor.js:528:1), <anonymous>:54:23)
    at Observable.subscribe (eval at <anonymous> (http://localhost:3000/dev/vendor.js:153:1), <anonymous>:42:22)
    at Observable._subscribe (eval at <anonymous> (http://localhost:3000/dev/vendor.js:153:1), <anonymous>:103:28)
    at MergeAllOperator.call (eval at <anonymous> (http://localhost:3000/dev/vendor.js:535:1), <anonymous>:63:23)
    at Observable.subscribe (eval at <anonymous> (http://localhost:3000/dev/vendor.js:153:1), <anonymous>:42:22)ErrorHandler.handleError
(unknown) ORIGINAL STACKTRACE:ErrorHandler.handleError
```

**Comment by brianghig** [comment]
False alarm from an issue identified on a fork. mean2-starter itself still looks good!

**Comment by brianghig** [comment]
Turns out this was a problem with zone.js v0.7.3. Pulling the latest 0.7.4 version works fine. https://github.com/angular/zone.js/issues/554
